Homework14: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #12
Opened 2024-06-22 13:28 UTC by MarieAmbrazhei

2024-06-22 21:16 UTC, Stml89 requested changes

2024-06-22 21:16 UTC, Stml89 commented on homework_14/homework_14_2.py
> +    def expression(self, input_expr):
not bad

2024-06-22 21:16 UTC, Stml89 commented on homework_14/homework_14_2.py
> +assert calculator.exponentiation(Decimal('2'), Decimal('3')) == '2 ^ 3 = 8'
Internally you are using it as a number, so you can use it here as well
```suggestion
assert calculator.summary(3, 2) == '3 + 2 = 5'
assert calculator.subtraction(5, 2) == '5 - 2 = 3'
assert calculator.multiplication(3, 2) == '3 * 2 = 6'
assert calculator.division(3, 2) == '3 / 2 = 1.5'
assert calculator.division(5, 0) == 'Error! Division by zero!'
assert calculator.exponentiation(2, 3) == '2 ^ 3 = 8'
```

2024-06-22 21:16 UTC, Stml89 commented on homework_14/homework_14_2.py
> +assert calculator.exponentiation(Decimal('2'), Decimal('3')) == '2 ^ 3 = 8'
You have implemented tests for all internal methods, which is really nice!

2024-06-23 14:03 UTC, MarieAmbrazhei commented on homework_14/homework_14_1.py
> +add_result_info(file_path='student.txt', info=entire_info)
fixed

2024-06-28 18:25 UTC, Stml89 approved these changes

2024-06-29 17:10 UTC, merged