Homework20: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #13
Opened 2024-07-14 20:46 UTC by MarieAmbrazhei

2024-07-16 19:32 UTC, Stml89 requested changes

2024-07-16 19:32 UTC, Stml89 commented on homework20/test_library_fuctionality.py
> +        self.assertIn('134527', User.taken_books)
Add something like: `Successfully verified <...>`

2024-07-16 19:32 UTC, Stml89 commented on requirements.txt
do you need all of those libraries?

2024-07-17 15:57 UTC, MarieAmbrazhei commented on homework20/test_library_fuctionality.py
> +        self.assertIn('134527', User.taken_books)
added

2024-07-19 20:16 UTC, Stml89 commented on requirements.txt
it fetches all libs that you have installed

2024-07-19 21:13 UTC, MarieAmbrazhei commented on requirements.txt
got it. done!

2024-07-21 06:51 UTC, Stml89 requested changes

2024-07-21 06:51 UTC, Stml89 commented on homework20/test_library_fuctionality.py
> +                          900, "Allen Downey ")
You have created those books but not using them

2024-07-21 06:51 UTC, Stml89 commented on homework20/test_library_fuctionality.py
> +                 f' additional info: {self.books.get(isbn)}')
```suggestion
        """Test that a user cannot take a book that is already taken."""
        log.info('User tries to take an already taken book with {self.book1.isbn} isbn')
        self.user_1.take_book({self.book1.isbn})
        self.assertFalse(self.user_2.take_book(self.book1.isbn))
        log.info(f'Successfully verified: book with {{self.book1.isbn}} is unavailable,'
                 f' additional info: {self.books.get({self.book1.isbn})}')
```

2024-07-22 13:31 UTC, MarieAmbrazhei commented on homework20/test_library_fuctionality.py
> +                 f' additional info: {self.books.get(isbn)}')
done

2024-07-23 19:44 UTC, Stml89 approved these changes

2024-07-27 21:16 UTC, merged