Homework21: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #14
Opened 2024-07-19 14:54 UTC by MarieAmbrazhei

2024-07-19 17:49 UTC, MarieAmbrazhei commented
Sergey, I added a report which I invoke with the command pytest homework21/tests/test_library_functionality.py --html-log-level=WARNING.
This way you can check the log level in the HTML file.

2024-07-23 18:40 UTC, Stml89 requested changes

2024-07-23 18:40 UTC, Stml89 commented on .pylintrc
Since you are using `pylint.yaml`, you can move those rules to it and delete this file

2024-07-23 18:40 UTC, Stml89 commented on mypy.ini
Add it to `mypy.yaml` and remove this file

2024-07-23 18:40 UTC, Stml89 commented on homework21/tests/test_library_functionality.py
> +    del user
if you have `conftest.py` move fixture to this file

2024-07-23 18:40 UTC, Stml89 commented on homework21/tests/test_library_functionality.py
> +def test_take_book_positive(user_1):
```suggestion
def test_take_book_positive(user_1, setup_books):
```

2024-07-23 18:40 UTC, Stml89 commented on homework21/tests/test_library_functionality.py
> +    assert user_1.take_book('134527'), ('Failed to take the book with'
and use book from `setup_book` fixture

2024-07-23 18:40 UTC, Stml89 commented on homework21/tests/test_bank_functionality.py
> +    log.info('Successfully verified deposit calculation')
those 2 tests can be combine into 1 with `pytest.mark.parametrize`

2024-07-24 19:06 UTC, MarieAmbrazhei commented on .pylintrc
done

2024-07-24 19:06 UTC, MarieAmbrazhei commented on mypy.ini
done

2024-07-24 19:07 UTC, MarieAmbrazhei commented on homework21/tests/test_library_functionality.py
> +    del user
done

2024-07-24 19:07 UTC, MarieAmbrazhei commented on homework21/tests/test_library_functionality.py
> +def test_take_book_positive(user_1):
done

2024-07-24 19:08 UTC, MarieAmbrazhei commented on homework21/tests/test_library_functionality.py
> +    assert user_1.take_book('134527'), ('Failed to take the book with'
done!

2024-07-24 19:08 UTC, MarieAmbrazhei commented on homework21/tests/test_bank_functionality.py
> +    log.info('Successfully verified deposit calculation')
done

2024-07-27 15:13 UTC, Stml89 approved these changes

2024-07-30 15:47 UTC, merged