Homework8: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #5
Opened 2024-05-29 14:15 UTC by MarieAmbrazhei

2024-05-31 20:17 UTC, Stml89 requested changes

2024-05-31 20:17 UTC, Stml89 commented on homework8.py
> +        hidden_four_digit_num = input("ENTER A FOUR-DIGIT NUMBER: ")
user can enter non-unique number

2024-05-31 20:17 UTC, Stml89 commented on homework8.py
> +print(count_missed_statues(statues))
use assert better then print() here to check that everything works as expected

2024-05-31 20:52 UTC, MarieAmbrazhei commented on homework8.py
> +        hidden_four_digit_num = input("ENTER A FOUR-DIGIT NUMBER: ")
added validation of unique digits as well as attempt count = 5

2024-05-31 20:56 UTC, MarieAmbrazhei commented on homework8.py
> +print(count_missed_statues(statues))
fixed

2024-06-01 17:17 UTC, Stml89 approved these changes

2024-06-01 17:17 UTC, Stml89 commented on homework8.py
> +        hidden_four_digit_num = input("ENTER A FOUR-DIGIT NUMBER: ")
the user can guess the number as much as he can

2024-06-01 17:34 UTC, MarieAmbrazhei commented on homework8.py
> +        hidden_four_digit_num = input("ENTER A FOUR-DIGIT NUMBER: ")
The idea is to give the user only 5 attempts to enter a non-unique  number and an unlimited number of attempts to enter a valid number.

2024-06-01 17:37 UTC, merged