Homework9: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #6
Opened 2024-05-31 17:54 UTC by MarieAmbrazhei

2024-06-01 19:36 UTC, Stml89 requested changes

2024-06-01 19:36 UTC, Stml89 commented on homework9.py
> +print(validate_card('4561261212345464'))
1/ use `assert` instead of `print()`
2/ card number - int, not str

2024-06-01 19:36 UTC, Stml89 commented on homework9.py
> +    if len(seq_int) - len(set(seq_int)) > 1:
what is the porpoise of this `if` condition?

2024-06-02 11:09 UTC, MarieAmbrazhei commented on homework9.py
> +print(validate_card('4561261212345464'))
1. added assert
2. fixed datatype

2024-06-02 11:21 UTC, MarieAmbrazhei commented on homework9.py
> +    if len(seq_int) - len(set(seq_int)) > 1:
the purpose is to skip verification if our list contains more than 1 duplicate. For instance, we have [1, 2, 1, 2], there are two duplicates so if we delete one element, we still have duplicate in our list, thus  given list cant have strictly ascending order.

2024-06-06 20:03 UTC, Stml89 approved these changes
Fix comments, and you can merge PR

2024-06-07 16:44 UTC, MarieAmbrazhei commented on homework9.py
> +# assert validate_card(4561261212345467)
sorry, fixed it.

2024-06-07 16:44 UTC, MarieAmbrazhei commented on homework9.py
> +print(can_be_ascending_by_removing_one([1, 2, 3]))
done.

2024-06-07 16:45 UTC, MarieAmbrazhei commented on homework9.py
> +print(find_opposite_number(10, 9))
done.

2024-06-07 16:46 UTC, MarieAmbrazhei commented on homework9.py
Got it! The next homework will be done using separate files.

2024-06-07 16:55 UTC, MarieAmbrazhei commented on homework9.py
*This HW was separated as well

2024-06-07 17:02 UTC, merged