Homework11: Marie Ambrazhei
MarieAmbrazhei/python_course pull request #8
Opened 2024-06-07 21:42 UTC by MarieAmbrazhei

2024-06-08 07:49 UTC, Stml89 requested changes

2024-06-08 07:49 UTC, Stml89 commented on homework11/homework11_1.py
> +    print(e)
Just 
```suggestion

assert result_of_validate(2, 4) == <expected value>
```

2024-06-08 07:49 UTC, Stml89 commented on homework11/homework11_4.py
> +        result = func(n)
It is better to define variable inside

```suggestion
    def wrapper(n):
        cached_results = {}
        if cached_results.get(n) is not None:
            return cached_results[n]
        result = func(n)
```

2024-06-08 07:49 UTC, Stml89 commented on homework11/homework11_2.py
> +        return func(*args)
You do not need to call `func` 2 times

2024-06-08 08:36 UTC, MarieAmbrazhei commented on homework11/homework11_4.py
> +        result = func(n)
Sorry, but its not clear, if I move cached_result inside wrapper , I have something like: {}
{}
{}
{}
But if I use cached_result as global variable I have: {}
{1: 1}
{1: 1, 0: 0, 2: 1}
{1: 1, 0: 0, 2: 1, 3: 2}.
Are you sure that is good idea to place it cached_result inside wrapper? If so, I will move it inside the wrapper. Sorry but I am a little confused with this task :(((

2024-06-08 08:37 UTC, MarieAmbrazhei commented on homework11/homework11_1.py
> +    print(e)
fixed

2024-06-08 08:38 UTC, MarieAmbrazhei commented on homework11/homework11_2.py
> +        return func(*args)
fixed

2024-06-16 09:12 UTC, Stml89 approved these changes
Fix it and you are good

2024-06-16 09:12 UTC, Stml89 commented on homework11/homework11_4.py
> +        result = func(n)
My bad, it should be like this:
```
def cache(func):
    cached_results = {}  # словарь для хранения закэшированных результатов

    def wrapper(*args):
        if args in cached_results:  # проверяем, есть ли результат в кэше
            return cached_results[args]
        result = func(*args)  # вызываем функцию и сохраняем результат
        cached_results[args] = result  # сохраняем результат в кэше
        return result

    return wrapper
```

2024-06-16 10:49 UTC, merged